{{ template "vault.serverServiceAccountEnabled" . }}
{{- $kubeVersion := .Capabilities.KubeVersion.Version }}
{{- if .serverServiceAccountEnabled -}}
{{ if semverCompare ">= 1.24.0-0" $kubeVersion }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault.serviceAccount.name" . }}-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ template "vault.serviceAccount.name" . }}
type: kubernetes.io/service-account-token
{{ end }}
{{ end }}